name:                 rubiks
version:              0.1.0.0
visibility:           public
id:                   rubiks-0.1.0.0-inplace
key:                  rubiks-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           zenoelioleone@gmail.com
author:               Zeno Leonardi
category:             Game
abi:                  inplace
exposed:              True
exposed-modules:      Model Move MyLib Scrambler
import-dirs:
    /home/zeno/school/inf221/rubiks/dist-newstyle/build/x86_64-linux/ghc-9.6.7/rubiks-0.1.0.0/build

library-dirs:
    /home/zeno/school/inf221/rubiks/dist-newstyle/build/x86_64-linux/ghc-9.6.7/rubiks-0.1.0.0/build

library-dirs-static:
    /home/zeno/school/inf221/rubiks/dist-newstyle/build/x86_64-linux/ghc-9.6.7/rubiks-0.1.0.0/build

dynamic-library-dirs:
    /home/zeno/school/inf221/rubiks/dist-newstyle/build/x86_64-linux/ghc-9.6.7/rubiks-0.1.0.0/build

data-dir:             /home/zeno/school/inf221/rubiks/.
hs-libraries:         HSrubiks-0.1.0.0-inplace
depends:
    base-4.18.3.0
    random-1.3.1-96049d861c5cae5a2e0709c1f05c99719e37b57efc5219aa2082985cbcd1b545

haddock-interfaces:
    /home/zeno/school/inf221/rubiks/dist-newstyle/build/x86_64-linux/ghc-9.6.7/rubiks-0.1.0.0/doc/html/rubiks/rubiks.haddock

haddock-html:
    /home/zeno/school/inf221/rubiks/dist-newstyle/build/x86_64-linux/ghc-9.6.7/rubiks-0.1.0.0/doc/html/rubiks
